version: '3.7'                                                                  
services:
  vcn:
    build: "."    
    restart: "always"
    healthcheck:
      test: "ps waux | grep -v grep | grep verify"
      interval: "5s"
      timeout: "5s"
      retries: "5"
      start_period: "5s"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
