version: '3.7'
services:
  vcn:
    build:
      context: "."
      dockerfile: "Dockerfile.prometheus"
    restart: "always"
    healthcheck:
      test: "ps waux | grep -v grep | grep verify"
      interval: "5s"
      timeout: "5s"
      retries: "5"
      start_period: "5s"
    volumes:
      - "share:/share:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  nginx:
    image: "nginx:1.15.7-alpine"
    ports:
      - "8080:5000"
    volumes:
      - "share:/share:ro"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
volumes:
  share:
